import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const read=path=>readFileSync(new URL(path,import.meta.url),'utf8');
const url=source=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText).toString('base64');
const libUrl=url(read('../lib/content-hub.ts'));
const lib=await import(libUrl);
const apiSource=read('../app/api/content-hub/route.ts').replace(/import \{ NextResponse \} from 'next\/server';/,"const NextResponse={json:(body,options)=>Response.json(body,options)};").replace(/import \{ getD1,getWorkspaceIdentity,ensureSchema,getMediaBucket \} from '@\/lib\/workspace';/,"const getD1=()=>globalThis.hubTest.db;const getWorkspaceIdentity=async()=>globalThis.hubTest.user?{userId:globalThis.hubTest.user}:null;const ensureSchema=async()=>{};const getMediaBucket=()=>null;").replace(/import \{ ensurePlanningSchema \} from '@\/lib\/planning';/,'const ensurePlanningSchema=async()=>{};').replace("'@/lib/content-hub'",JSON.stringify(libUrl));
const api=await import(url(apiSource));
function setup(){const sql=new DatabaseSync(':memory:');sql.exec(read('../drizzle/0020_content_hub.sql'));sql.exec(`CREATE TABLE journal_entries(id TEXT,user_id TEXT,type TEXT,title TEXT,content TEXT,recorded_at TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE checkins(id TEXT,user_id TEXT,type TEXT,note TEXT,created_at TEXT);CREATE TABLE planning_records_v2(id TEXT,user_id TEXT,type_key TEXT,title TEXT,content TEXT,feeling TEXT,recorded_at TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE task_outputs(id TEXT,user_id TEXT,task_type TEXT,title TEXT,content TEXT,feeling TEXT,created_at TEXT);CREATE TABLE journal_images(id TEXT,user_id TEXT,journal_id TEXT,object_key TEXT,content_type TEXT);CREATE TABLE record_images(id TEXT,user_id TEXT,record_id TEXT,record_type TEXT,object_key TEXT,content_type TEXT);`);
 const db={prepare(query){let values=[];const s={bind(...v){values=v;return s;},async run(){return{meta:{changes:Number(sql.prepare(query).run(...values).changes)}};},async first(){return sql.prepare(query).get(...values)||null;},async all(){return{results:sql.prepare(query).all(...values)};}};return s;},async batch(items){sql.exec('BEGIN');try{const result=[];for(const item of items)result.push(await item.run());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};globalThis.hubTest={db,user:'alice'};return{sql,db};}
const post=async body=>{const r=await api.POST(new Request('http://localhost/api/content-hub',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));return{status:r.status,...await r.json()};};

test('legacy records migrate once without altering sources, preserving approved categories and images',async()=>{const {sql,db}=setup();sql.exec(`INSERT INTO checkins VALUES('book','alice','reading','Book note','2026-08-12T04:00:00Z');INSERT INTO journal_entries VALUES('f84de8fc-0039-4481-8598-5383226b4fc2','alice','creation','Copy','Full copy','2026-09-07','a','a');INSERT INTO planning_records_v2 VALUES('10b6db11-9880-49f2-96fc-14a8f86c80b4','alice','health','Health','Baseline','','2026-08-21','a','a');INSERT INTO record_images VALUES('image','alice','book','checkin','alice/image','image/png');`);await lib.migrateIndependentRecords(db,'alice');await lib.migrateIndependentRecords(db,'alice');assert.equal(sql.prepare('SELECT COUNT(*) n FROM hub_documents').get().n,3);assert.equal(sql.prepare("SELECT kind FROM hub_documents WHERE title='Copy'").get().kind,'xhs_copy');assert.equal(sql.prepare("SELECT kind FROM hub_documents WHERE title='Health'").get().kind,'diary');assert.equal(sql.prepare("SELECT kind FROM hub_documents WHERE title='Book note'").get().kind,'reading_note');assert.equal(sql.prepare('SELECT COUNT(*) n FROM hub_images').get().n,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM checkins').get().n,1);sql.close();});

test('document saves are idempotent, revision guarded and private; invalid dates/types are rejected',async()=>{const {sql}=setup();const body={action:'save-document',kind:'diary',title:'Diary',content:'Body',date:'2026-09-26',requestId:'one'};const a=await post(body);assert.equal(a.status,200);assert.equal((await post(body)).id,a.id);assert.equal(sql.prepare('SELECT COUNT(*) n FROM hub_documents').get().n,1);assert.equal((await post({...body,id:a.id,revision:1,content:'Edited'})).status,200);assert.equal((await post({...body,id:a.id,revision:1})).status,409);assert.equal(JSON.parse(sql.prepare('SELECT versions FROM hub_documents').get().versions)[0].content,'Body');assert.equal((await post({...body,date:'2026-02-30'})).status,400);assert.equal((await post({...body,kind:'learning'})).status,400);globalThis.hubTest.user='bob';assert.equal((await post({...body,id:a.id,revision:2})).status,404);assert.equal((await api.GET()).status,200);assert.equal((await (await api.GET()).json()).documents.length,0);globalThis.hubTest.user=null;assert.equal((await api.GET()).status,401);sql.close();});

test('vocabulary preserves sources and examples, checks once per submission and excludes mastered words',async()=>{const {sql}=setup();const body={action:'import-words',title:'Words',date:'2026-09-26',requestId:'a',entries:[{word:'Persist',pos:'verb',meaning:'坚持',example:'I persist.'},{word:'Recall',meaning:'回忆',example:'I recall it.'}]};assert.equal((await post(body)).status,200);await post(body);await post({...body,requestId:'b',entries:[{word:'persist',pos:'verb',meaning:'坚持',example:'We persist.'}]});assert.equal(sql.prepare('SELECT COUNT(*) n FROM hub_words').get().n,2);assert.equal(sql.prepare('SELECT COUNT(*) n FROM hub_word_lists').get().n,2);const word=sql.prepare("SELECT id FROM hub_words WHERE word='Persist'").get().id;assert.equal((await post({action:'start-review',count:3,requestId:'bad'})).status,400);
 for(let i=0;i<3;i++){const r=await post({action:'start-review',wordId:word,requestId:'r'+i});assert.equal(r.status,200);assert.equal((await post({action:'finish-review',id:r.id})).status,400);await post({action:'answer-review',id:r.id,wordId:word,answer:'remembered'});await post({action:'answer-review',id:r.id,wordId:word,answer:'forgotten'});await post({action:'finish-review',id:r.id});await post({action:'finish-review',id:r.id});}
 let snapshot=await (await api.GET()).json();assert.equal(snapshot.words[0].id,word);assert.equal(snapshot.words[0].forgotten,3);assert.equal(snapshot.words[0].checks,3);assert.equal(snapshot.words[0].difficult,true);
 await post({action:'master-word',id:word,mastered:true});assert.equal((await post({action:'start-review',wordId:word,requestId:'mastered'})).status,400);await post({action:'master-word',id:word,mastered:false});const r=await post({action:'start-review',wordId:word,requestId:'restored'});await post({action:'master-word',id:word,mastered:true});assert.equal((await post({action:'finish-review',id:r.id})).status,200);snapshot=await (await api.GET()).json();assert.equal(snapshot.words.find(w=>w.id===word).checks,3);assert.equal(snapshot.lists.flatMap(l=>JSON.parse(l.entries)).filter(e=>e.wordId===word).length,2);sql.close();});
