"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';
import { HubDoc, Word, WordList, Review, ListEntry, parse } from '@/lib/content-hub';

type Snapshot={documents:HubDoc[];images:{id:string;document_id:string}[];words:Word[];lists:WordList[];reviews:Review[]};
type Mode='records'|'vocabulary'|'media';
const labels:Record<string,string>={reading_note:'读书笔记',inspiration:'灵感',diary:'日记',xhs_idea:'小红书 · 灵感',xhs_copy:'小红书 · 文案',overseas_idea:'海外自媒体 · 灵感',overseas_copy:'海外自媒体 · 文案'};
const statusLabels:Record<string,string>={draft:'草稿',final:'已定稿',published:'已发布',selected:'已选用',archived:'已归档'};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Makassar',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function request(body:Record<string,unknown>){const response=await fetch('/api/content-hub',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'操作失败，请重试');return data as {ok:boolean;id?:string;url?:string};}

export default function ContentHub({mode}:{mode:Mode}){
 const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[date,setDate]=useState(''),[page,setPage]=useState(1),[statusFilter,setStatusFilter]=useState('');
 const [kind,setKind]=useState('reading_note'),[platform,setPlatform]=useState('xhs'),[section,setSection]=useState('idea'),[editing,setEditing]=useState<HubDoc|'new'|null>(null),[seed,setSeed]=useState<Partial<HubDoc>>({}),[selected,setSelected]=useState<string|null>(null);
 const load=useCallback(async()=>{const r=await fetch('/api/content-hub',{cache:'no-store'});const value=await r.json();if(!r.ok)throw new Error(value.error||'暂时无法加载');setData(value);},[]);
 useEffect(()=>{const refresh=()=>{const params=new URLSearchParams(window.location.search);setSelected(params.get('entry'));void load().catch(e=>setError(e.message));};refresh();window.addEventListener('wen-path-content-updated',refresh);return ()=>window.removeEventListener('wen-path-content-updated',refresh);},[load]);
 useEffect(()=>{if(data)window.dispatchEvent(new Event('wen-path-content-ready'));},[data]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);setSelected(params.get('entry'));},[]);
 useEffect(()=>{setPage(1);},[kind,platform,section,query,date,mode]);
 async function act(body:Record<string,unknown>){setBusy(true);setError('');try{const result=await request(body);await load();return result;}catch(e){setError(e instanceof Error?e.message:'操作失败');return null;}finally{setBusy(false);}}
 if(!data)return <section className="planning-panel"><h2>{error||'正在加载…'}</h2>{error&&<button className="soft-button" onClick={()=>{setError('');void load().catch(e=>setError(e.message));}}>重新加载</button>}</section>;
 const selectedKind=mode==='media'?`${platform}_${section}`:kind;
 const docs=data.documents.filter(d=>d.kind===selectedKind&&(!statusFilter||d.status===statusFilter)&&(!date||d.date===date)&&`${d.title} ${d.content}`.toLowerCase().includes(query.toLowerCase()));
 const detail=selected?data.documents.find(d=>d.id===selected):undefined;
 return <>
  <header className="page-header"><div><p>{mode==='records'?'留住阅读、想法与生活':mode==='media'?'从选题到定稿':'每天积累，反复记住'}</p><h1>{mode==='records'?'记录':mode==='media'?'自媒体':'英语生词表'}</h1></div>{mode!=='vocabulary'&&<button className="primary-button" onClick={()=>{setSeed({});setEditing('new');}}>＋ {mode==='records'?'添加记录':section==='idea'?'记录灵感':'添加文案'}</button>}</header>
  {error&&<p role="alert" className="hub-notice hub-global-notice">{error}</p>}
  {mode==='vocabulary'?<Vocabulary data={data} busy={busy} act={act} apiError={error}/>:<>
   {mode==='media'&&<div className="filter-row" aria-label="自媒体平台">{[['xhs','小红书'],['overseas','海外自媒体']].map(([key,label])=><button key={key} className={platform===key?'active':''} onClick={()=>setPlatform(key)}>{label}</button>)}</div>}
   <div className="filter-row" aria-label="内容分类">{(mode==='records'?[['reading_note','读书笔记'],['inspiration','灵感'],['diary','日记']]:[['idea','灵感'],['copy','文案']]).map(([key,label])=><button key={key} className={(mode==='records'?kind:section)===key?'active':''} onClick={()=>mode==='records'?setKind(key):setSection(key)}>{label}</button>)}</div>
   <div className="hub-toolbar"><input aria-label="搜索记录" placeholder="搜索标题或正文" value={query} onChange={e=>setQuery(e.target.value)}/><input aria-label="按日期筛选" type="date" value={date} onChange={e=>setDate(e.target.value)}/>{date&&<button className="text-button" onClick={()=>setDate('')}>清除日期</button>}{mode==='media'&&<select aria-label="按状态筛选" value={statusFilter} onChange={e=>{setStatusFilter(e.target.value);setPage(1);}}><option value="">所有状态</option>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>}<span>{docs.length} 条</span></div>
   <div className="hub-documents">{docs.slice((page-1)*20,page*20).map(doc=><article className="planning-panel hub-document" key={doc.id}><div className="panel-heading"><span>{doc.date}{mode==='media'?` · ${statusLabels[doc.status]||doc.status}`:''}</span><button className="text-button" onClick={()=>setEditing(doc)}>编辑</button></div><button className="hub-title" onClick={()=>setSelected(doc.id)}>{doc.title}</button><p className="hub-excerpt">{doc.content}</p>{data.images.filter(i=>i.document_id===doc.id).slice(0,1).map(i=><img className="hub-cover" key={i.id} src={`/api/content-image/${encodeURIComponent(i.id)}`} alt={doc.title}/>)}{mode==='media'&&section==='idea'&&<button className="soft-button" onClick={()=>{setSeed({kind:`${platform}_copy`,title:doc.title,meta:JSON.stringify({ideaId:doc.id}),content:''});setEditing('new');}}>由此选题写文案</button>}</article>)}</div>
   {!docs.length&&<div className="empty-list"><b>还没有{labels[selectedKind]}</b><p>在应用中讨论好内容后，可以先在这里粘贴保存。</p></div>}
   {docs.length>20&&<div className="hub-toolbar"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page} / {Math.ceil(docs.length/20)}</span><button disabled={page*20>=docs.length} onClick={()=>setPage(p=>p+1)}>下一页</button></div>}
  </>}
  {detail&&<HubDialog title={detail.title} close={()=>setSelected(null)}><div className="hub-document"><p>{labels[detail.kind]} · {detail.date}</p><p className="hub-body">{detail.content}</p>{data.images.filter(i=>i.document_id===detail.id).map(i=><img className="hub-cover" key={i.id} src={`/api/content-image/${encodeURIComponent(i.id)}`} alt={detail.title}/>)}{Object.entries(parse<Record<string,string>>(detail.meta,{})).filter(([key,value])=>value&&key!=='ideaId').map(([key,value])=><p key={key}><b>{{account:'平台 / 账号',language:'语言',tags:'话题标签',source:'聊天来源',publishedAt:'发布时间',publishedUrl:'发布链接'}[key]||key}：</b>{value}</p>)}{parse<HubDoc[]>(detail.versions,[]).length>0&&<details><summary>历史版本</summary>{parse<HubDoc[]>(detail.versions,[]).slice().reverse().map(v=><section key={v.revision}><h3>版本 {v.revision} · {v.title}</h3><p className="hub-body">{v.content}</p></section>)}</details>}<button className="soft-button" onClick={()=>{setEditing(detail);setSelected(null);}}>编辑</button></div></HubDialog>}
  {editing&&<DocumentEditor doc={editing==='new'?undefined:editing} initial={{kind:selectedKind,...seed}} images={data.images} close={()=>setEditing(null)} saved={async()=>{await load();setEditing(null);}}/>}
 </>;
}

function HubDialog({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=ref.current;dialog?.showModal();return ()=>dialog?.close();},[]);
 return <dialog ref={ref} className="dialog hub-dialog hub-native-dialog" aria-label={title} onCancel={e=>{e.preventDefault();close();}}><button className="dialog-close" aria-label="关闭" onClick={close}>×</button><h2>{title}</h2>{children}</dialog>;
}
function DocumentEditor({doc,initial,images,close,saved}:{doc?:HubDoc;initial:Partial<HubDoc>;images:{id:string;document_id:string}[];close:()=>void;saved:()=>Promise<void>}){
 const [kind,setKind]=useState(doc?.kind||initial.kind||'diary'),[title,setTitle]=useState(doc?.title||initial.title||''),[content,setContent]=useState(doc?.content||initial.content||''),[date,setDate]=useState(doc?.date||today()),[status,setStatus]=useState(doc?.status||'draft'),[meta,setMeta]=useState<Record<string,string>>(parse(doc?.meta||initial.meta||'{}',{})),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmDelete,setConfirmDelete]=useState(false),[persisted,setPersisted]=useState<{id:string;revision:number}|null>(doc?{id:doc.id,revision:doc.revision}:null),[requestId]=useState(()=>crypto.randomUUID());
 const social=/^(xhs|overseas)_/.test(kind);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{const result=await request({action:'save-document',id:persisted?.id,revision:persisted?.revision,requestId,kind,title,content,date,status,meta});const id=result.id!;setPersisted({id,revision:(persisted?.revision||0)+1});if(files.length){const form=new FormData();form.append('id',id);files.forEach(f=>form.append('images',f));const r=await fetch('/api/content-hub',{method:'POST',body:form});if(!r.ok){const info=await r.json();throw new Error(`文字已保存；${info.error||'图片上传失败'}。可重试上传。`);}setFiles([]);}await saved();}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
 return <HubDialog title={doc?'编辑内容':'保存内容'} close={close}><form onSubmit={submit}>{error&&<p role="alert" className="hub-notice">{error}</p>}<label><span>分类</span><select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(labels).filter(([key])=>social?/^(xhs|overseas)_/.test(key):['reading_note','inspiration','diary'].includes(key)).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label><span>标题</span><input required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span>日期</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>正文</span><textarea required maxLength={30000} value={content} onChange={e=>setContent(e.target.value)} placeholder={social?'粘贴讨论后的选题或文案':'写下或粘贴你的记录'}/></label>{social&&<><label><span>状态</span><select value={status} onChange={e=>setStatus(e.target.value)}>{(kind.endsWith('_idea')?['draft','selected','archived']:['draft','final','published']).map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></label>{[['account','平台 / 账号'],['language','语言'],['tags','话题标签'],['source','聊天来源（可选）'],['publishedAt','实际发布时间（可选）'],['publishedUrl','发布链接（可选）']].map(([key,label])=><label key={key}><span>{label}</span><input maxLength={1000} value={meta[key]||''} onChange={e=>setMeta(m=>({...m,[key]:e.target.value}))}/></label>)}</>}<label><span>图片（最多6张，每张8MB）</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><small>已有 {images.filter(i=>i.document_id===doc?.id).length} 张，新选 {files.length} 张</small></label><div className="dialog-actions">{doc?<button type="button" className="danger-button" disabled={busy} onClick={async()=>{if(!confirmDelete){setConfirmDelete(true);return;}setBusy(true);try{await request({action:'delete-document',id:doc.id});await saved();}catch(e){setError(e instanceof Error?e.message:'删除失败');}finally{setBusy(false);}}}>{confirmDelete?'确认移除':'移除记录'}</button>:<span/>}<button className="primary-button" disabled={busy}>{busy?'保存中…':'保存'}</button></div></form></HubDialog>;
}

type Act=(body:Record<string,unknown>)=>Promise<{id?:string}|null>;
function Vocabulary({data,busy,act,apiError}:{data:Snapshot;busy:boolean;act:Act;apiError:string}){
 const [view,setView]=useState('active'),[search,setSearch]=useState(''),[listId,setListId]=useState(''),[count,setCount]=useState(10),[importing,setImporting]=useState(false),[reviewId,setReviewId]=useState(''),[index,setIndex]=useState(0),[showWord,setShowWord]=useState<string|null>(null),[page,setPage]=useState(1),[listDate,setListDate]=useState('');
 const list=data.lists.find(l=>l.id===listId),entries=list?parse<ListEntry[]>(list.entries,[]):[],ids=list?new Set(entries.map(e=>e.wordId)):null;
 const candidates=data.words.filter(w=>!w.mastered&&(!ids||ids.has(w.id))),visible=data.words.filter(w=>(view==='list-detail'?true:view==='mastered'?Boolean(w.mastered):!w.mastered)&&(view!=='difficult'||w.difficult)&&(!ids||ids.has(w.id))&&`${w.word} ${w.meaning}`.toLowerCase().includes(search.toLowerCase()));
 const review=data.reviews.find(r=>r.id===reviewId),items=review?parse<Word[]>(review.items,[]):[],answers=review?parse<Record<string,string>>(review.answers,{}):{},current=items[index];
 const wordDetail=data.words.find(w=>w.id===showWord);
 useEffect(()=>{setPage(1);},[view,search,listId]);
 const start=async(wordId?:string)=>{const result=await act({action:'start-review',listId,wordId,count,requestId:crypto.randomUUID()});if(result?.id){setReviewId(result.id);setIndex(0);}};
 return <>
  <div className="hub-toolbar"><button className="primary-button" onClick={()=>setImporting(true)}>＋ 保存词表与造句</button><select aria-label="词表范围" value={listId} onChange={e=>setListId(e.target.value)}><option value="">所有词表</option>{data.lists.map(l=><option key={l.id} value={l.id}>{l.date} · {l.title}</option>)}</select></div>
  <div className="filter-row">{[['active','待复习'],['difficult','易忘词'],['mastered','已掌握'],['lists','全部词表'],['history','检查历史']].map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}>{label}</button>)}</div>
  <section className="planning-panel hub-review-setup"><div><h3>检查记忆</h3><p>只看单词回忆意思。易忘词优先，其余随机选取。</p></div><label>检查数量<input aria-label="检查数量" type="number" min={1} max={Math.max(1,candidates.length)} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><span>可选 {candidates.length} 个</span><button className="primary-button" disabled={busy||count<1||count>candidates.length||!Number.isInteger(count)} onClick={()=>void start()}>开始检查</button></section>
  {view==='lists'&&<div className="hub-toolbar"><input aria-label="按学习日期筛选" type="date" value={listDate} onChange={e=>setListDate(e.target.value)}/>{listDate&&<button onClick={()=>setListDate('')}>清除日期</button>}</div>}
  {view==='lists'?<div className="hub-documents">{data.lists.filter(l=>!listDate||l.date===listDate).map(l=><article className="planning-panel" key={l.id}><small>{l.date}</small><h3>{l.title}</h3><p>{parse<ListEntry[]>(l.entries,[]).length} 条收录 · {l.source||'未填写来源'}</p><button className="soft-button" onClick={()=>{setListId(l.id);setView('list-detail');}}>查看词表</button></article>)}{!data.lists.length&&<p>还没有词表，保存聊天中整理的单词和造句后会显示在这里。</p>}</div>:view==='history'?<section className="planning-panel">{data.reviews.map(r=>{const a=Object.values(parse<Record<string,string>>(r.answers,{}));return <article className="hub-history" key={r.id}><div><b>{r.created_at.slice(0,10)} · {r.status==='active'?'未完成':'已完成'}</b><p>记得 {a.filter(x=>x==='remembered').length} · 忘记 {a.filter(x=>x==='forgotten').length} · 跳过 {a.filter(x=>x==='skipped').length}</p></div><button className="soft-button" onClick={()=>{setReviewId(r.id);setIndex(0);}}>{r.status==='active'?'继续检查':'查看结果'}</button></article>;})}{!data.reviews.length&&<p>尚无检查记录。</p>}</section>:<>
  <div className="hub-toolbar"><input aria-label="搜索生词" placeholder="搜索单词或释义" value={search} onChange={e=>setSearch(e.target.value)}/><span>{visible.length} 个词</span>{list&&<span>{list.title}</span>}</div>
  <div className="hub-word-list">{visible.slice((page-1)*30,page*30).map(word=><article className="planning-panel hub-word" key={word.id}><div><button className="hub-title" onClick={()=>void start(word.id)} disabled={busy||Boolean(word.mastered)}>{word.word}</button><small>{word.pos}{word.mastered?' · 已掌握':word.difficult?' · 易忘':''}</small><p>{word.meaning}</p><small>检查 {word.checks} 次 · 忘记 {word.forgotten} 次</small></div><div className="hub-word-actions"><button className="soft-button" onClick={()=>setShowWord(word.id)}>造句与来源</button><button className="text-button" disabled={busy} onClick={()=>void act({action:'master-word',id:word.id,mastered:!word.mastered})}>{word.mastered?'恢复复习':'完全记住，移出复习'}</button></div></article>)}</div>{!visible.length&&<div className="empty-list">这里还没有单词。</div>}{visible.length>30&&<div className="hub-toolbar"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>上一页</button><span>{page} / {Math.ceil(visible.length/30)}</span><button disabled={page*30>=visible.length} onClick={()=>setPage(p=>p+1)}>下一页</button></div>}
  </>}
  {wordDetail&&<HubDialog title={wordDetail.word} close={()=>setShowWord(null)}><p>{wordDetail.meaning}</p>{data.lists.flatMap(l=>parse<ListEntry[]>(l.entries,[]).filter(e=>e.wordId===wordDetail.id).map((entry,i)=><section key={`${l.id}:${i}`} className="hub-example"><h3>{l.date} · {l.title}</h3><p>{entry.meaning}</p><p className="hub-body">{entry.example||'暂无造句'}</p>{entry.correction&&<p>修订：{entry.correction}</p>}{l.source&&<small>来源：{l.source}</small>}</section>))}</HubDialog>}
  {review&&<HubDialog title={review.status==='completed'?'检查结果':'检查记忆'} close={()=>setReviewId('')}>{apiError&&<p role="alert" className="hub-notice">{apiError}</p>}
   {review.status==='completed'?<div>{items.map(w=><p key={w.id}><b>{w.word}</b> · {{remembered:'记得',forgotten:'忘记',skipped:'已掌握，跳过'}[answers[w.id]]||'未作答'} · {w.meaning}</p>)}</div>:current?<div className="hub-flashcard"><small>{index+1} / {items.length}</small><h3>{current.word}</h3>{data.words.find(w=>w.id===current.id)?.mastered?<p>这个词已掌握，本轮提交时会跳过。</p>:<><p>回忆这个词的意思，再选择：</p><div className="hub-toolbar" role="radiogroup" aria-label="记忆结果">{[['remembered','记得'],['forgotten','忘记']].map(([value,label])=><button key={value} role="radio" aria-checked={answers[current.id]===value} className={answers[current.id]===value?'primary-button':'soft-button'} disabled={busy} onClick={()=>void act({action:'answer-review',id:review.id,wordId:current.id,answer:value})}>{label}</button>)}</div>{answers[current.id]&&<div className="hub-answer"><b>{current.meaning}</b>{data.lists.flatMap(l=>parse<ListEntry[]>(l.entries,[]).filter(e=>e.wordId===current.id).map((e,i)=><p key={`${l.id}:${i}`}>{e.example}{e.correction&&` → ${e.correction}`}</p>))}</div>}</>}<div className="hub-toolbar"><button className="soft-button" disabled={index===0} onClick={()=>setIndex(i=>i-1)}>上一个</button><button className="soft-button" disabled={index===items.length-1} onClick={()=>setIndex(i=>i+1)}>下一个</button><button className="primary-button" disabled={busy||items.some(w=>!answers[w.id]&&!data.words.find(l=>l.id===w.id)?.mastered)} onClick={()=>void act({action:'finish-review',id:review.id})}>提交本轮</button></div><small>关闭后可以在检查历史中继续；提交前可改选。</small></div>:null}
  </HubDialog>}
  {importing&&<WordImporter close={()=>setImporting(false)} busy={busy} act={act} apiError={apiError}/>}
 </>;
}
function WordImporter({close,busy,act,apiError}:{close:()=>void;busy:boolean;act:Act;apiError:string}){
 const [title,setTitle]=useState(''),[date,setDate]=useState(today()),[source,setSource]=useState(''),[text,setText]=useState(''),[requestId]=useState(()=>crypto.randomUUID());
 let entries:{word:string;pos:string;meaning:string;example:string;correction:string}[]=[],error='';
 if(text.trim())try{if(text.trim().startsWith('[')){const input=JSON.parse(text);if(!Array.isArray(input))throw new Error();entries=input.map(row=>({word:String(row.word||''),pos:String(row.pos||''),meaning:String(row.meaning||''),example:String(row.example||''),correction:String(row.correction||'')}));}else entries=text.split('\n').filter(row=>row.trim()).map(row=>{const [word='',meaning='',example='',pos='',correction='']=row.split('\t');return {word:word.trim(),meaning:meaning.trim(),example:example.trim(),pos:pos.trim(),correction:correction.trim()};});if(entries.some(e=>!e.word||!e.meaning)||entries.length>200)error='每行需有单词和释义，每份最多200行。';}catch{error='格式无法识别，请使用制表符分列或有效 JSON 数组。';}
 return <HubDialog title="保存词表与造句" close={close}>{apiError&&<p role="alert" className="hub-notice">{apiError}</p>}<form onSubmit={async e=>{e.preventDefault();const r=await act({action:'import-words',title,date,source,entries,requestId});if(r)close();}}><label><span>词表标题</span><input required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span>学习日期</span><input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>聊天来源（可选）</span><input maxLength={1000} value={source} onChange={e=>setSource(e.target.value)}/></label><label><span>单词、释义与造句</span><textarea required value={text} onChange={e=>setText(e.target.value)} placeholder={'每行一词，用 Tab 分隔：单词\t释义\t造句\t词性\t修订句'}/></label><details><summary>粘贴格式说明</summary><p>可让聊天应用输出 JSON 数组，字段为 word、meaning、example、pos、correction；后3项可选。相同单词与词性会合并，造句和来源会保留。</p><code>{'[{"word":"persist","meaning":"坚持","example":"I persist in learning English.","pos":"verb"}]'}</code></details>{error&&<p role="alert">{error}</p>}{entries.length>0&&!error&&<div className="hub-import-preview"><h3>预览 · {entries.length} 条</h3>{entries.slice(0,10).map((w,i)=><p key={i}><b>{w.word}</b> · {w.meaning}<br/>{w.example}</p>)}{entries.length>10&&<p>其余 {entries.length-10} 条也将保存。</p>}</div>}<button className="primary-button" disabled={busy||!entries.length||Boolean(error)}>{busy?'保存中…':'保存词表'}</button></form></HubDialog>;
}
